// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package ggrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	// 定义方法
	GetAuthInfo(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetAuthInfo(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/service.UserService/GetAuthInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	// 定义方法
	GetAuthInfo(context.Context, *AuthRequest) (*AuthResponse, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) GetAuthInfo(context.Context, *AuthRequest) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthInfo not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_GetAuthInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetAuthInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.UserService/GetAuthInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetAuthInfo(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAuthInfo",
			Handler:    _UserService_GetAuthInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pbfiles/user.proto",
}

// NetSpaceServiceClient is the client API for NetSpaceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NetSpaceServiceClient interface {
	GetNetSpaceByUserUUID(ctx context.Context, in *NetSpaceRequest, opts ...grpc.CallOption) (*NetSpaceResponse, error)
}

type netSpaceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNetSpaceServiceClient(cc grpc.ClientConnInterface) NetSpaceServiceClient {
	return &netSpaceServiceClient{cc}
}

func (c *netSpaceServiceClient) GetNetSpaceByUserUUID(ctx context.Context, in *NetSpaceRequest, opts ...grpc.CallOption) (*NetSpaceResponse, error) {
	out := new(NetSpaceResponse)
	err := c.cc.Invoke(ctx, "/service.NetSpaceService/GetNetSpaceByUserUUID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NetSpaceServiceServer is the server API for NetSpaceService service.
// All implementations must embed UnimplementedNetSpaceServiceServer
// for forward compatibility
type NetSpaceServiceServer interface {
	GetNetSpaceByUserUUID(context.Context, *NetSpaceRequest) (*NetSpaceResponse, error)
	mustEmbedUnimplementedNetSpaceServiceServer()
}

// UnimplementedNetSpaceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNetSpaceServiceServer struct {
}

func (UnimplementedNetSpaceServiceServer) GetNetSpaceByUserUUID(context.Context, *NetSpaceRequest) (*NetSpaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNetSpaceByUserUUID not implemented")
}
func (UnimplementedNetSpaceServiceServer) mustEmbedUnimplementedNetSpaceServiceServer() {}

// UnsafeNetSpaceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NetSpaceServiceServer will
// result in compilation errors.
type UnsafeNetSpaceServiceServer interface {
	mustEmbedUnimplementedNetSpaceServiceServer()
}

func RegisterNetSpaceServiceServer(s grpc.ServiceRegistrar, srv NetSpaceServiceServer) {
	s.RegisterService(&NetSpaceService_ServiceDesc, srv)
}

func _NetSpaceService_GetNetSpaceByUserUUID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NetSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NetSpaceServiceServer).GetNetSpaceByUserUUID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.NetSpaceService/GetNetSpaceByUserUUID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NetSpaceServiceServer).GetNetSpaceByUserUUID(ctx, req.(*NetSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NetSpaceService_ServiceDesc is the grpc.ServiceDesc for NetSpaceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NetSpaceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.NetSpaceService",
	HandlerType: (*NetSpaceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNetSpaceByUserUUID",
			Handler:    _NetSpaceService_GetNetSpaceByUserUUID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pbfiles/user.proto",
}
